server:
  port: 8090

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/SmartMES
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true